config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#all'
  
  #session routes
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  get '/profil', to:'users#edit', as: :profil
  patch '/profil', to: 'users#update'
  get '/favorites', to: 'posts#favorites', as: :favorites

  #register routes
  get '/register', to: 'users#new', as: :register
  post '/register', to: 'users#create'

  resources :users, only: [:new] do
    member do
      get 'confirm'
    end
  end
  resources :sessions, only: [:new, :destroy]
  resources :posts do
    member do 
      get 'to_favorite', to: 'posts#to_favorite'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image; ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  #associations
  belongs_to :user
  has_and_belongs_to_many :users

  #valdations
  validates :user_id, presence: true

  #scope
  scope :online, ->(online) { where(online: online)}
  scope :for_user, ->(user_id) { where(user_id: user_id)}
  scope :insert_author, -> { includes(:user)}

  mount_uploader :image; ImageUploader
  
  #methods de class
  def is_author?(author)
    user_id == author
  end

end

app/models/user.rb
class User < ApplicationRecord
  #relations
  has_many :posts
  has_and_belongs_to_many :posts

  #validations
  validates :username, presence: true, 
    uniqueness: { case_sensitive: false }, 
    format: { with: /\A[a-zA-Z0-9_]{2,20}\z/, message: "ne doit contenir que des eractères alphanumeriques" }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, 
    length: {maximum: 255}, 
    format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }
  validates :password, presence: true, 
    length: { minimum:6,  maximum: 50}
  
  
  mount_uploader :avatar, AvatarUploader
  has_secure_password
  has_secure_token :token

  def to_session
    {id: id}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :danger
  before_action :only_login_in
  helper_method :logged_in?, :current_user

  private
  def only_login_in
    unless logged_in?
      redirect_to login_path
    end
  end

  def logged_in?
    current_user.present?
  end

  def current_user
    return nil if !session || !session[:auth] || !session[:auth]['id']
    return @_user||User.find_by_id( session[:auth]['id'] )
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:edit, :edit, :update, :destroy]

  def index
    @posts = Post.insert_author.online(true).for_user(current_user.id).order(id: :desc).all
  end

  def show
    @post = Post.find(params[:id])
  end

  def all
    @posts = Post.insert_author.online(true).order(updated_at: :desc).all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(get_params)
    @post.user_id = current_user.id
    if(@post.valid?)
      @post.save
      RegisterMailer.post_confirm(current_user, @post).deliver_now
      redirect_to posts_path, success: "Publication créé avec succes"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(get_params)
      redirect_to posts_path, success: "Publication mise à jour avec succes"
    else
      render 'edit'
    end
  end

  def to_favorite
    @post = Post.find(params[:id])
    if @post.present?
      current_user.posts << @post unless current_user.posts.include?(@post)
      puts 'ajouter'
    end
    redirect_to root_path
  end

  def favorites
    @favorites = current_user.posts
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end


  private
  def set_post
    @post = Post.find(params[:id])
  end

  def get_params
    params.require(:post).permit(:content, :image, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :only_login_in, only: [:new, :create]
  def index
  end

  def new
  end

  def create
    user_params = params.require(:user)
    @user = User.where(username: user_params[:username] ).or(User.where(email: user_params[:email])).first
    if @user && @user.authenticate(user_params[:password])
      session[:auth] = @user.to_session
      redirect_to root_path
    else
      flash.now[:danger] = "Identifient ou mot de passe incorrecte"
      render 'new'
    end
  end

  def destroy
    session.destroy
    redirect_to login_path, success: "Deconnecter avec succes"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :only_login_in, only: [:new, :create, :confirm]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(get_params)
    if(@user.valid?)
      @user.save
      #RegisterMailer.confirm(@user).deliver_now
      redirect_to login_path, success: "Inscription effectuée avec succes. Vous recevrez un mail afin de valider votre inscription"
    else
      render 'new'
    end
  end

  def confirm
    @user = User.find(params[:id])
    if @user.present?
      @user.update_attributes(token: params[:token], validated: true)
      @user.save(validate: false)
      redirect_to register_path
    else
      render 'confirm'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    param = params.require(:user).permit(:firstname, :lastname, :avatar, :avatar_cache)
    @user.update_attributes(param)
    @user.save(validate: false)
    redirect_to profil_path, success: "Profil mis à jour avec succes"
  end

  private
  def get_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= Rails.application.config.site[:name] %> </title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
          <h5 class="my-0 mr-md-auto font-weight-normal"> <%= Rails.application.config.site[:name] %> </h5>
          <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
            <a class="p-2 text-dark" href=" <%= root_path%> ">Acceuil</a>
            <% if logged_in? %>
              <div class="dropdown text-end">
                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle show" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="true">
                  <img src=" <%= current_user.avatar.present? ? current_user.avatar : 'https://github.com/mdo.png' %> " alt="mdo" width="32" height="32" class="rounded-circle">
                </a>
                <ul class="dropdown-menu text-small show" aria-labelledby="dropdownUser1" data-popper-placement="bottom-end">
                  <li><a class="dropdown-item" href="<%=posts_path%>">Mes publications</a></li>
                  <li><a class="dropdown-item" href="<%=favorites_path%>">Favories</a></li>
                  <li><a class="dropdown-item" href="<%=profil_path%>">Profil</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item text-danger" href="<%= new_session_path %>" data-method="DELETE">Deconnexion</a></li>
                </ul>
              </div>
            <% else %>
              <a class="btn btn-outline-primary" href="<%=login_path%>">Se connecter</a>
            <%end%>
          </nav>
        </div>
      </div>
    </nav>
   
    <div class="container">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for post, html: { multipart: true }  do |f| %>
    <div class="mb-3">
      <%= f.text_area :content, class: 'form-control' %>
    </div>
    <%= image_tag(post.image.url) if post.image && post.image.url %>
    <div class="mb-3">
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
    </div>
    <div class="mb-3 text-end">
      <%= f.submit 'Poster', class: 'btn btn-primary btn-lg' ,data: {confirm: 'Validez-vous la publication?'}, disable_with: 'Submiting...' %>
    </div>
  <% end %>

app/views/posts/_post.html.erb
<div class="container-fluid">
  <%= image_tag(post.image.url, class:'img-fluid img-larg') if post.image && post.image.url %>
  <%= content_tag('small',"Par: #{post.user.username==current_user.username ? 'Vous' : post.user.username}", class:'text-left') if post.user && post.user.username %>
</div>

<div class="container">
  <p>
    <%= post.content %>
  </p>
  <div class="card-footer">
    <% if current_user.posts.include?(post) %>
      <a href="<%= to_favorite_post_path(post.id) %>"><i class="fa fa-heart fa-2x" aria-hidden="true"></i></a>
    <% else %>
      <a href="<%= to_favorite_post_path(post.id) %>"><i class="fa fa-heart-o fa-2x" aria-hidden="true"></i></a>
    <% end %>
  </div>
  <%if post.is_author?(current_user.id)%>
    <div class="card-footer">
      <div class="row">
        <div class="col-sm">
          <a href="<%= edit_post_path(id: post.id) %>" class="btn-link">Editer</a>
        </div>
        <div class="col-sm">
          <a href="<%= post_path(id: post.id) %>" 
          data-confirm="Voulez-vous reelement effectuer cette action?"
          data-method="DELETE"
          class="btn-link text-danger">Supprimer</a>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/posts/_posts.html.erb
<div class="row">
  <%posts.each do |post|%>
    <div class="col-md-12">
      <div class="card mb-4">
        <div class="card-header">
          <%= content_tag('p',"Par: #{post.user.username==current_user.username ? 'Vous' : post.user.username}", class:'text-left') if post.user && post.user.username %>
        </div>
        <div class="card-body">
          <%= image_tag(post.image.url, class:'img-fluid') if post.image && post.image.url %>
          <p>
            <%= post.content %>
          </p>
        </div>
        <div class="card-footer">
          <% if current_user.posts.include?(post) %>
            <a href="<%= to_favorite_post_path(post.id) %>"><i class="fa fa-heart fa-2x" aria-hidden="true"></i></a>
          <% else %>
            <a href="<%= to_favorite_post_path(post.id) %>"><i class="fa fa-heart-o fa-2x" aria-hidden="true"></i></a>
          <% end %>
        </div>
        <div class="card-footer">
          <div class="row">
            <div class="col-sm">
              <a href="<%= post_path(id: post.id) %>" class="btn-link">Lire...</a>
            </div>
            <%if post.is_author?(current_user.id)%>
              <div class="col-sm">
                <a href="<%= edit_post_path(id: post.id) %>" class="btn-link">Editer</a>
              </div>
              <div class="col-sm">
                <a href="<%= post_path(id: post.id) %>" 
                data-confirm="Voulez-vous reelement effectuer cette action?"
                data-method="DELETE"
                class="btn-link text-danger">Supprimer</a>
              </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/posts/all.html.erb
<%= render 'posts', {posts: @posts} %>

app/views/posts/edit.html.erb
<div class="container">
  <p>
  editer</p>
  <%= render 'form', {post: @post} %>
</div>

app/views/posts/favorites.html.erb
<div class="container">
  <%= render 'posts', {posts: @favorites} %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row text-end">
    <div class="col-md">
      <a href="<%= new_post_path%>" class="btn btn-success">Ajouter une publication</a>
    </div>
  </div>
  <div class="row">
    <div class="col-md">
      <p class="text-center h4">Mes publications</p>
    </div>
  </div>
  <%= render 'posts', {posts: @posts} %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <p class="text-center h2">créer une nouvelle publication</p>
  <%= render 'form', {post: @post} %>
</div>

app/views/posts/show.html.erb
<%= render 'post', {post: @post} %>

app/views/users/edit.html.erb
<div class="container">
  <div class="">
    <%= form_for @user, url: profil_path, html: { multipart: true, }  do |f| %>
      <div class="row text-center">
        <div class="col-md">
          <%= image_tag( @user.avatar.url, width: '200px', height: '200px', class:'rounded-circle' ) if @user.avatar.present? %>
          <%= content_tag('p', @user.username, class: "text-center bold") %>
          <%= content_tag('small', @user.email, class: "text-center bold") %>
        </div>
      </div>
      <div class="mb-3">
        <%= f.text_field :firstname, placeholder: "Nom", class:"form-control form-control-sm" %>
      </div>
      <div class="mb-3">
        <%= f.text_field :lastname, placeholder: "Prénom", class:"form-control form-control-sm" %>
      </div>
      <div class="mb-3">
        <%= f.file_field :avatar, class: "form-control form-control-sm" %>
        <%= f.hidden_field :avatar_cache %>
      </div>
      <div class="mb-3 text-end">
        <%= f.submit 'Mettre à jour', class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container ">
  <div class="vertical-center">
    <div class="row">
      <div class="col-sm-8 offset-2">
        <div class="card">
          <div class="card-body">
            <h4 class="text-center">Fakebook</h4>

            <% if flash[:success] %>
              <div class="alert alert-success">
                <%= flash[:success] %>
              </div>
            <%end%>

            <% if flash[:danger] %>
              <div class="alert alert-danger">
                <%= flash[:danger] %>
              </div>
            <%end%>

            <% if @user.errors.any? %>
              <div class="alert alert-danger">
                <ul>
                  <% @user.errors.full_messages.each do |m| %>
                    <li> <%= m %> </li>
                  <%end%>
                </ul>
              </div>
            <%end%>



            <%= form_for @user,url: register_path, html: { multipart: true }  do |f| %>
              <div class="mb-3">
                <%= f.text_field :username, class:'form-control', placeholder: "Nom d'utilisateur" %>
              </div>
              <div class="mb-3">
                <%= f.text_field :email, type: 'e-mail', class:'form-control', placeholder: "E-mail" %>
              </div>
              <div class="mb-3">
                <%= f.password_field :password, class:'form-control', placeholder: "Mot de passe" %>
              </div>
              <div class="mb-3">
                <%= f.password_field :password_confirmation, class:'form-control', placeholder: "Confirmer le mot de passe" %>
              </div>
              <div class="d-grid gap-2">
                <%= f.submit "S'inscrire", disable_with: 'Submiting...', class:'btn btn-success' %>
              </div>
            <% end %>
            <div class="text-center">
              <a href="<%= login_path %>" class="btn  btn-link">Se connecter</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
</div>